<div class="item">
<br/>
<h1 style="text-align:center; font-size:22px;">Programme 2013-2014</h1>
<p class="pdate">FALL SEMESTER</p>
<!--p class="pdate">Wednesday 9 October</p>
<p class="pevent">Loic Hemard, Inter Rhône</p-->
<p class="pdate">Saturday 26 October</p>
<p class="pevent">Kevin Judd, Greywacke, Marlborough</p>
<p class="pdate">Wednesday 6 November</p>
<p class="pevent">Stéphanie de Boüard, Château Angélus</p>
<p class="pdate">Tuesday 12 November</p>
<p class="pevent">Paul Pontallier &amp; Thibault Pontallier, Château Margaux</p>
<!--p class="pdate">Wednesday 20 November</p>
<p class="pevent">Nimród Kovács, David Varga-Sabjan, Hungary Tasting</p-->
<p class="pdate">Friday 22 November</p>
<p class="pevent">Viña Errázuriz</p>
<p class="pdate">Saturday 23 November</p>
<p class="pevent">Château Lynch-Bages</p>
<p class="pdate">Wednesday 27 November</p>
<p class="pevent">Champagne Lanson</p>
<p class="pdate">March 2014</p>
<p class="pevent">Château Cos d'Estournel</p>
<p class="pdate">TBC</p>
<p class="pevent">Tenuta di Trinoro</p>
<p class="pevent">Clarendon Hills</p>
<p class="pevent">Felton Road</p>
<p class="pevent">Greenock Creek</p>
<p class="pevent">Bouchard Père &amp; Fils</p>
</div>
